// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6f7qPyMy6Fb0r4jI8nQjHAxA2p5r0E5U',
    appId: '1:821306580475:android:f8af12c903281be3b27f5e',
    messagingSenderId: '821306580475',
    projectId: 'esp32-7f82e',
    databaseURL: 'https://esp32-7f82e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-7f82e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ypMptQhicgzkpc-5K18n5UiBXRaB_Mg',
    appId: '1:821306580475:ios:730b919d325cd0fab27f5e',
    messagingSenderId: '821306580475',
    projectId: 'esp32-7f82e',
    databaseURL: 'https://esp32-7f82e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-7f82e.firebasestorage.app',
    iosBundleId: 'com.example.homeAutomation',
  );
}
